"""Render approved test cases as a readable Playwright Test (.spec.ts) file.

The pipeline executes cases through the test-runner's step DSL, not this file; the
spec is the human-reviewable (and copy-into-a-repo-able) form of exactly the same steps,
rendered deterministically so the same cases always produce the same file.
"""

from __future__ import annotations

import json
import re

from rag_backend.agents.schemas import Locator, TestCase, TestStep


def _ts_string(value: str) -> str:
    # JSON string syntax is valid TypeScript string syntax (escapes quotes, newlines,
    # backslashes and control characters).
    return json.dumps(value, ensure_ascii=False)


def _options(entries: dict[str, str]) -> str:
    return "{ " + ", ".join(f"{key}: {value}" for key, value in entries.items()) + " }"


def render_locator(locator: Locator) -> str:
    exact = {"exact": "true"} if locator.exact else {}
    if locator.strategy == "role":
        options = {"name": _ts_string(locator.name)} if locator.name else {}
        options |= exact
        suffix = f", {_options(options)}" if options else ""
        return f"page.getByRole({_ts_string(locator.value)}{suffix})"
    if locator.strategy == "label":
        suffix = f", {_options(exact)}" if exact else ""
        return f"page.getByLabel({_ts_string(locator.value)}{suffix})"
    if locator.strategy == "testid":
        return f"page.getByTestId({_ts_string(locator.value)})"
    if locator.strategy == "text":
        suffix = f", {_options(exact)}" if exact else ""
        return f"page.getByText({_ts_string(locator.value)}{suffix})"
    return f"page.locator({_ts_string(locator.value)})"


def render_step(step: TestStep) -> str:
    value = step.value or ""
    if step.action == "goto":
        return f"await page.goto(new URL({_ts_string(value)}, BASE_URL).toString());"
    if step.action == "expect_url":
        return f"await expect(page).toHaveURL(new RegExp({_ts_string(re.escape(value))}));"
    assert step.locator is not None  # guaranteed by TestStep's validator
    target = render_locator(step.locator)
    if step.action == "fill":
        return f"await {target}.fill({_ts_string(value)});"
    if step.action == "click":
        return f"await {target}.click();"
    if step.action == "expect_visible":
        return f"await expect({target}).toBeVisible();"
    if step.action == "expect_hidden":
        return f"await expect({target}).toBeHidden();"
    if step.action == "expect_text":
        return f"await expect({target}).toContainText({_ts_string(value)});"
    return f"await expect({target}).toHaveValue({_ts_string(value)});"


def render_spec_ts(cases: list[TestCase], base_url: str, suite_title: str, run_id: str) -> str:
    lines = [
        "import { test, expect } from '@playwright/test';",
        "",
        f"// Generated by the Agents pipeline (run {run_id}) from business-approved test cases.",
        "// Do not edit by hand: re-run the pipeline instead.",
        f"const BASE_URL = {_ts_string(base_url)};",
        "",
        f"test.describe({_ts_string(suite_title)}, () => {{",
    ]
    for case in cases:
        lines.append(
            f"  test({_ts_string(f'{case.case_id} — {case.title}')}, async ({{ page }}) => {{"
        )
        lines.append(f"    // Rules: {', '.join(case.source_rule_ids) or '-'}")
        lines.append(f"    // Expected: {case.expected}".replace("\n", " "))
        lines.extend(f"    {render_step(step)}" for step in case.steps)
        lines.append("  });")
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    lines.append("});")
    lines.append("")
    return "\n".join(lines)
