from __future__ import annotations

from rag_backend.agents.schemas import Locator, TestCase, TestStep
from rag_backend.agents.spec_render import render_locator, render_spec_ts


def test_render_spec_ts_produces_expected_playwright_file() -> None:
    case = TestCase(
        case_id="TC-REG-001",
        title="Successful registration",
        expected="Banner shown",
        source_rule_ids=["BR-003"],
        steps=[
            TestStep(action="goto", value=""),
            TestStep(
                action="fill", locator=Locator(strategy="label", value="First name"), value="Long"
            ),
            TestStep(
                action="click", locator=Locator(strategy="role", value="button", name="Register")
            ),
            TestStep(
                action="expect_text",
                locator=Locator(strategy="testid", value="success-banner"),
                value="Account 123",
            ),
            TestStep(action="expect_url", value="/myweb/"),
        ],
    )

    spec = render_spec_ts([case], "http://myweb:8080/myweb/", "Register Account", "run-1")

    assert spec == (
        "import { test, expect } from '@playwright/test';\n"
        "\n"
        "// Generated by the Agents pipeline (run run-1) from business-approved test cases.\n"
        "// Do not edit by hand: re-run the pipeline instead.\n"
        'const BASE_URL = "http://myweb:8080/myweb/";\n'
        "\n"
        'test.describe("Register Account", () => {\n'
        '  test("TC-REG-001 — Successful registration", async ({ page }) => {\n'
        "    // Rules: BR-003\n"
        "    // Expected: Banner shown\n"
        '    await page.goto(new URL("", BASE_URL).toString());\n'
        '    await page.getByLabel("First name").fill("Long");\n'
        '    await page.getByRole("button", { name: "Register" }).click();\n'
        '    await expect(page.getByTestId("success-banner")).toContainText("Account 123");\n'
        '    await expect(page).toHaveURL(new RegExp("/myweb/"));\n'
        "  });\n"
        "});\n"
    )


def test_render_locator_escapes_quotes_and_backslashes() -> None:
    locator = Locator(strategy="text", value='He said "hi" \\ bye', exact=True)

    assert render_locator(locator) == 'page.getByText("He said \\"hi\\" \\\\ bye", { exact: true })'


def test_render_locator_css_falls_back_to_page_locator() -> None:
    assert render_locator(Locator(strategy="css", value="#email-error")) == (
        'page.locator("#email-error")'
    )
